name: academic
display_name: "Academic Presentation"
description: "Template for academic and research presentations"
slide_masters:
  - title_slide
  - section_header
  - bullet_slide
placeholders:
  - name: title
    shape_id: 0
  - name: content
    shape_id: 1
styles:
  font: Calibri
  primary_color: "#003366"
  background_color: "#FFFFFF"